<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>async与await</title>
</head>

<body>
	<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
	<!-- 
		1. async修饰的函数
				这其实是副作用，不会把返回值拿来用的：	函数的返回值为promise对象
					Promise实例的结果由async函数执行的返回值决定

		2. await表达式
					await右侧的表达式一般为Promise实例对象, 但也可以是其它的值
					(1).如果表达式是Promise实例对象, await后的返回值是promise成功的值
					(2).如果表达式是其它值, 直接将此值作为await的返回值  实际开发中，不会直接这样写
		
		3. 注意:
				await必须写在async函数中, 但async函数中可以没有await   实际开发中 用了async 都要用await的
				如果await的Promise实例对象失败了, 就会抛出异常, 需要通过try...catch来捕获处理
 -->
	<script>
		const p1 = new Promise((resolve, reject) => {
			setTimeout(() => {
				resolve('a')
			}, 1000)
		})
		const p2 = new Promise((resolve, reject) => {
			setTimeout(() => {
				resolve('一些错误')
			}, 2000)
		})
		const p3 = new Promise((resolve, reject) => {
			setTimeout(() => {
				resolve('c')
			}, 6000)
		})


			; (async () => {
				try {
					const result1 = await p1
					console.log(result1);    //相当于.then后面成功的回调
					const result2 = await p2
					console.log(result2);    //相当于.then后面成功的回调
					const result3 = await p3
					console.log(result3);    //相当于.then后面成功的回调
				} catch (error) {
					console.log(error);
				}
			})()

		//测试async
		/* async function demo() {
			const result = await p1
			console.log(result);
		}
		demo() */

	</script>
</body>

</html>